# Generated by Django 6.0.8 on 2026-08-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_core", "0003_apigatewayhttpapi_cloudtrailtrail_cognitouserpool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsecretsmanagersecret",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="secretsmanagersecret",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
