# Generated by Django 6.0.8 on 2026-09-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_core", "0005_retire_renamed_edge_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="elb",
            name="lb_type",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="historicalelb",
            name="lb_type",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
