# Generated by Django 6.0.8 on 2026-09-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_core', '0010_network_plane_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='elasticachecluster',
            name='cluster_arn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='historicalelasticachecluster',
            name='cluster_arn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='historicalrdsinstance',
            name='db_instance_arn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='rdsinstance',
            name='db_instance_arn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='cloudfrontdistribution',
            name='origin_access',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcloudfrontdistribution',
            name='origin_access',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicallambdafunction',
            name='vpc_security_group_ids',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicallambdafunction',
            name='vpc_subnet_ids',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lambdafunction',
            name='vpc_security_group_ids',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lambdafunction',
            name='vpc_subnet_ids',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='acmcertificate',
            index=models.Index(fields=['certificate_arn'], name='nk_aws_core__aws_acm_c_3c9b44c'),
        ),
        migrations.AddIndex(
            model_name='alb',
            index=models.Index(fields=['lb_arn'], name='nk_aws_core__aws_alb'),
        ),
        migrations.AddIndex(
            model_name='apigatewayhttpapi',
            index=models.Index(fields=['api_arn'], name='nk_aws_core__aws_apiga_c0c5378'),
        ),
        migrations.AddIndex(
            model_name='availabilityzone',
            index=models.Index(fields=['zone_id'], name='nk_aws_core__aws_az'),
        ),
        migrations.AddIndex(
            model_name='cloudfrontdistribution',
            index=models.Index(fields=['distribution_arn'], name='nk_aws_core__aws_cloud_5c6aef0'),
        ),
        migrations.AddIndex(
            model_name='cloudtrailtrail',
            index=models.Index(fields=['trail_arn'], name='nk_aws_core__aws_cloud_fb1d146'),
        ),
        migrations.AddIndex(
            model_name='cloudwatchloggroup',
            index=models.Index(fields=['name'], name='nk_aws_core__aws_cloud_c8fed67'),
        ),
        migrations.AddIndex(
            model_name='cognitouserpool',
            index=models.Index(fields=['pool_id'], name='nk_aws_core__aws_cogni_f272ea8'),
        ),
        migrations.AddIndex(
            model_name='dynamodbtable',
            index=models.Index(fields=['table_arn'], name='nk_aws_core__aws_dynam_924ccd2'),
        ),
        migrations.AddIndex(
            model_name='ecrrepository',
            index=models.Index(fields=['repository_arn'], name='nk_aws_core__aws_ecr_r_80e4538'),
        ),
        migrations.AddIndex(
            model_name='ecscluster',
            index=models.Index(fields=['cluster_arn'], name='nk_aws_core__aws_ecs_cluster'),
        ),
        migrations.AddIndex(
            model_name='ecsservice',
            index=models.Index(fields=['service_arn'], name='nk_aws_core__aws_ecs_service'),
        ),
        migrations.AddIndex(
            model_name='ecstask',
            index=models.Index(fields=['task_arn'], name='nk_aws_core__aws_ecs_task'),
        ),
        migrations.AddIndex(
            model_name='ekscluster',
            index=models.Index(fields=['cluster_arn'], name='nk_aws_core__aws_eks_cluster'),
        ),
        migrations.AddIndex(
            model_name='elasticsearchdomain',
            index=models.Index(fields=['domain_arn'], name='nk_aws_core__aws_elast_f401eb2'),
        ),
        migrations.AddIndex(
            model_name='elb',
            index=models.Index(fields=['dns_name'], name='nk_aws_core__aws_elb'),
        ),
        migrations.AddIndex(
            model_name='eventbridgerule',
            index=models.Index(fields=['rule_arn'], name='nk_aws_core__aws_event_06336d3'),
        ),
        migrations.AddIndex(
            model_name='iamoidcprovider',
            index=models.Index(fields=['provider_arn'], name='nk_aws_core__aws_iam_o_b632b3c'),
        ),
        migrations.AddIndex(
            model_name='iampolicy',
            index=models.Index(fields=['policy_arn'], name='nk_aws_core__aws_iam_policy'),
        ),
        migrations.AddIndex(
            model_name='iamrole',
            index=models.Index(fields=['role_arn'], name='nk_aws_core__aws_iam_role'),
        ),
        migrations.AddIndex(
            model_name='iamuser',
            index=models.Index(fields=['user_arn'], name='nk_aws_core__aws_iam_user'),
        ),
        migrations.AddIndex(
            model_name='kmskey',
            index=models.Index(fields=['key_arn'], name='nk_aws_core__aws_kms_key'),
        ),
        migrations.AddIndex(
            model_name='lambdafunction',
            index=models.Index(fields=['function_arn'], name='nk_aws_core__aws_lambda'),
        ),
        migrations.AddIndex(
            model_name='networkfirewall',
            index=models.Index(fields=['firewall_arn'], name='nk_aws_core__aws_netwo_4beed17'),
        ),
        migrations.AddIndex(
            model_name='s3bucket',
            index=models.Index(fields=['bucket_arn'], name='nk_aws_core__aws_s3_bucket'),
        ),
        migrations.AddIndex(
            model_name='sagemakerendpoint',
            index=models.Index(fields=['endpoint_arn'], name='nk_aws_core__aws_sagem_4d54156'),
        ),
        migrations.AddIndex(
            model_name='secretsmanagersecret',
            index=models.Index(fields=['secret_arn'], name='nk_aws_core__aws_secre_0dfc177'),
        ),
        migrations.AddIndex(
            model_name='sqsqueue',
            index=models.Index(fields=['queue_arn'], name='nk_aws_core__aws_sqs_queue'),
        ),
        migrations.AddIndex(
            model_name='ssmparameter',
            index=models.Index(fields=['parameter_arn'], name='nk_aws_core__aws_ssm_parameter'),
        ),
        migrations.AddIndex(
            model_name='targetgroup',
            index=models.Index(fields=['target_group_arn'], name='nk_aws_core__aws_target_group'),
        ),
    ]
